apiVersion: v1
kind: Service
metadata:
  name: webui-service
  namespace: dual-rag
spec:
  selector:
    app: webui
  type: LoadBalancer
  ports:
    - name: http
      port: 3000
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui-deployment
  namespace: dual-rag
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
        - name: webui
          image: ghcr.io/open-webui/open-webui:main
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: OLLAMA_BASE_URL
              value: "http://ollama-service:11434"
            - name: WEBUI_AUTH
              value: "true"
            - name: RAG_API_BASE_URL
              value: "http://rag-service:8000"
            - name: WEBUI_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: webui-secrets
                  key: secret-key
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2"
          volumeMounts:
            - name: data
              mountPath: /app/backend/data
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
      volumes:
        - name: data
          emptyDir: {}

---
apiVersion: v1
kind: Secret
metadata:
  name: webui-secrets
  namespace: dual-rag
type: Opaque
stringData:
  secret-key: "change-this-to-a-random-secret-key"

