version: '3.9'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - rag-network

  webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_AUTH=true  # Enable authentication for security
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY:-change-this-secret-key}
      - RAG_API_BASE_URL=http://rag:8000
    volumes:
      - webui_data:/app/backend/data
    depends_on:
      ollama:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - rag-network

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --maxmemory 2gb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - rag-network

  rag:
    build:
      context: .
      dockerfile: ./rag/Dockerfile
    container_name: rag-service
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./rag/data:/app/data
      - ./rag/indexes:/app/indexes
      - ./rag/logs:/app/logs
      - ./workspace:/workspace
      - ./ui:/app/ui
    environment:
      - OLLAMA_API=http://ollama:11434
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=INFO
      - PYTHONUNBUFFERED=1
      - BRAVE_API_KEY=${BRAVE_API_KEY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - ENABLE_WEB_SEARCH=${ENABLE_WEB_SEARCH:-true}
      - ENABLE_GITHUB=${ENABLE_GITHUB:-true}
    depends_on:
      ollama:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge

volumes:
  ollama_models:
  webui_data:
  redis_data: